### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by BerkanYildiz** [everdox/InfinityHook#1]
I tried to compile this and not work help me please I'm china p coder

**Edit:** How do I compile .md file

**Comment by Akandesh** [comment]
Are you compiling it as x86/x64 and not Win32?

**Comment by Evilcry** [comment]
Are you joking right? infinityhook_sample.hpp is empty

**Comment by Akandesh** [comment]
yes.

**Comment by BerkanYildiz** [comment]
@Akandesh I'm compiling the .md as ARMv8, is it fine ?

**Comment by adrianyy** [comment]
Works for me, try restarting your PC.

**Comment by BerkanYildiz** [comment]
I tried restarting PC now PC wont boot, it stuck on Huawei logo, please help me you break PC me!!

![image](https://user-images.githubusercontent.com/15068742/61495267-c7a3fb00-a9b8-11e9-85b1-899ee74e4a09.png)

now it shows visit pvp n buy paste from russia peopole

**Comment by YangKi1902** [comment]
works for me, try reinstall your OS.

**Comment by wonderzdh** [comment]
> 我试图编译这个并没有工作帮助我，请我是中国编码员
> 
> **编辑：**如何编译.md文件

.md 是描述文件，目前该项目还未上传代码。请耐心等待。

**Comment by BerkanYildiz** [comment]
@wonderzdh r/woosh

**Comment by everdox** [comment]
Fixed. C&P friendly now. :trollface:

**Comment by DragonQuestHero** [comment]
@everdox awesome!
