### ISSUE TITLE
Does InfinityHook work on 32-bit windows OS? 

### ISSUE THREAD

**Issue by chen-bob** [everdox/InfinityHook#16]
Thanks in advance for your answer.

**Comment by BerkanYildiz** [comment]
No.

**Comment by chen-bob** [comment]
Thanks for your reply, BerkanYildiz. Do you think it is possible that InfinityHook be extended to support 32-bit Windows 7/10? Or there is some intrinsic characteristic of InfinityHook making it impossible to be applied on 32-bit OS?

**Comment by BerkanYildiz** [comment]
Sorry, when you said 32-bit the first thing that came to my mind was Windows 7 x86 and older versions like Vista.

I suppose ETW is implemented on Windows 10 x86 etc. You will have to get the data structures of certain things like the _WMI_LOGGER_CONTEXT struct (```dt nt!_WMI_LOGGER_CONTEXT```), and edit the sig-scan as iirc KVA and a few other stuff are not implemented in the x86 version.

If what you want to know is if it's possible, then check if ETW is implemented in your build of windows x86, if yes, then obviously it's possible.

Sorry for the vague response, but as I don't have a x86 a Windows, I can't really state anything.

**Comment by chen-bob** [comment]
You have already been very helpful with insights from kernel. Thanks a lot!
