### ISSUE TITLE
Memory leak in ImgGetBaseAddress

### ISSUE THREAD

**Issue by tandasat** [everdox/InfinityHook#5]
`Buffer` leaks in a successful path of `ImgGetBaseAddress`.

**Comment by BerkanYildiz** [comment]
Pushed a fix here : https://github.com/everdox/InfinityHook/pull/3/commits/fe3f012caa6f0f801e15b6a8363ceef7251c0253

**Comment by nmulasmajic** [comment]
Fixed in the newest commit. Thanks for reporting.

**Comment by tandasat** [comment]
It still leaks when `return ModuleInformation->ImageBase;` is taken :)

**Comment by nmulasmajic** [comment]
Refresh :).

**Comment by tandasat** [comment]
It's :magic:
