### ISSUE TITLE
Fix Bug Section

### ISSUE THREAD

**Issue by ivanpos2015** [everdox/InfinityHook#6]
sc_name = BuildNumber == 7600 ? ".rdata" : ".data";
PVOID SectionBase = ImgGetImageSection(NtBaseAddress, sc_name, &SizeOfSection);

Win10:
http://prntscr.com/ohxvlz
Win7 7600:
http://prntscr.com/ohxvsb

**Comment by nmulasmajic** [comment]
Fixed in the newest commit. Thanks for reporting.
